apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jssaui0nh-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:e24ca2f9bc4fe5ae3af7df343af493077c66449c@sha256:81c2a2ad8d55e0dd9dcc76df6c2ab1eb3ab1cc23ba5347845b19affb63317d7f
          name: container-image
